name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild ./usermode/cs2_webradar.sln /p:Configuration=release /p:Platform=x64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: usermode-build
        path: usermode/release/usermode.exe
